=== luatnguyenlonaldo/metalworld/web/WEB-INF/configs/difficult/difficult-for-product.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://xml.netbeans.org/schema/difficult-for-product"
           targetNamespace="http://xml.netbeans.org/schema/difficult-for-product"
           elementFormDefault="qualified">
    <xs:element name="difficultMappings" type="DifficultMappings"/>
    <xs:complexType name="DifficultMappings">
        <xs:sequence>
            <xs:element name="difficultMapping" type="DifficultMapping" 
                        minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="DifficultMapping">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="mapping" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== luatnguyenlonaldo/metalworld/web/WEB-INF/configs/difficult/difficult-for-product.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<difficultMappings
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://xml.netbeans.org/schema/difficult-for-product'
    xsi:schemaLocation='http://xml.netbeans.org/schema/difficult-for-product difficult-for-product.xsd'>
    <difficultMapping>
        <name>2</name>
        <mapping>dễ</mapping>
    </difficultMapping>
    <difficultMapping>
        <name>5</name>
        <mapping>trung bình</mapping>
    </difficultMapping>
    <difficultMapping>
        <name>9</name>
        <mapping>khó</mapping>
    </difficultMapping>
</difficultMappings>
